spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key:

admin:
  token:

naver:
  client-id:
  client-secret:
